import java.util.concurrent.*;
import java.util.*;

public class Task9 {
    public static void main(String[] args) throws Exception {
        ExecutorService executor = Executors.newFixedThreadPool(5);

        List<Callable<String>> tasks = new ArrayList<>();

        for (int i = 1; i <= 5; i++) {
            int id = i;
            tasks.add(() -> {
                Thread.sleep(1000);
                return "Report" + id + " generated by " + Thread.currentThread().getName();
            });
        }

        List<Future<String>> results = executor.invokeAll(tasks);

        for (Future<String> f : results) {
            System.out.println(f.get());
        }

        executor.shutdown();
    }
}
